### ISSUE TITLE
Update to use Salt 3005 release

### ISSUE THREAD

**Issue by kamwoods** [BitCurator/bitcurator-cli#2]
For Ubuntu 22.04 support, update to 3005. Build and test in 20.04 and 22.04 to verify. Additional notes on 3005 (for reference) at:

https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html

May need to update pip package refs?

**Comment by digitalsleuth** [comment]
Will most likely require updating for Jammy support (22.04), but not specifically for the CLI. The other issue might be available apt packages on Jammy as well. I can take a look at those this evening.

**Comment by kamwoods** [comment]
Yes...one small change I believe is required for the cli is in lines 237, 248, 259 of the js file the urls of the form:
https://repo.saltproject.io/py3 ...
now need to be of the form:
https://repo.salproject.io/salt/py3 ...

And changing the saltStackVersion ref to 3005. Building after these changes with Node 14.20.0 in Ubuntu 22.04.1 seems fine (aside from some ongoing deprecation warnings for request etc) and the resulting binary works as before. I've put these very minor changes in branch (UPDATE/cli) while continuing to test.

As you indicated there are various packages/repos that fail from the unmodified bitcurator-salt release when attempting this install in 22.04.1. For my own reference as well (not comprehensive, just a selection I noted so far):

- bctools.sls in /Tools can simply be removed; these tools are end of life (potential rewrite in Qt6 should the community indicate a strong desire for it in the future
- The key for the Siegfried repo is no longer valid; didn't have a chance to get updated key / test yet
- No jammy release files for sift and kitware?
- Some issue with dbus-launch? Maybe need the dbus-x11 package in 22.04? Saw in the log, not sure if this resulted from an earlier failure.

I didn't have the time earlier to ask specifically why sift, gift, and kitware repos were added, hazarding that they simply provided more modern or recently released packages for things we were previously compiling. From what I see, it's liblightgrep from sift, bulk_extractor and sleuthkit from gift, and cmake from kitware. Is that accurate?

**Comment by digitalsleuth** [comment]
Just tested everything and got it to work for both Focal and Jammy, with some minor changes. There are three packages not available in Jammy, and the SIFT repo isn't ready for Jammy yet (Erik is working on it).
Already accounted for the dbus-x11 issue as well.

SIFT was added for liblightgrep and bulk_extractor, GIFT was added for an updated sleuthkit, but could probably be removed. Kitware is actually fine, it failed because when after adding the siegfried repo failed, kitware couldn't be added due to the issue when adding the key.

I'll add the updates in a pull request for the salt states shortly. I'm testing the CLI now in both the desktop environments. Already built a new version yesterday, but wanted to make sure the states were up to date before testing the CLI.

**Comment by kamwoods** [comment]
Amazing, thanks! I'm ok with dropping GIFT for the time being if needed (particularly given that 22.04 has the recent/stable tsk 4.11.1 by default). Our *specific* requirements for tsk, libewf, and pytsk previously were to keep them playing nice with the increasingly outdated bitcurator-tools, but that's no longer an issue. I don't believe BitCurator has any other tools that demand a *particular* tsk.

**Comment by kamwoods** [comment]
Closing. Moving reminders/list to new issue on bitcurator-salt.
